### GET request to example server
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/

### GET Developers
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers

### GET Developers by Id
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers1

### ADD Developers
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Ian Nthuli",
  "techStack": ["Kotlin", "Jetpack-compose", "Spring-Boot","XML"]
}

### Login User
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/login
Content-Type: application/json

{
  "username": "walter_white",
  "password": "securePassword123"
}


### Register User
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/register
Content-Type: application/json

{
  "username": "walter_white",
  "password": "securePassword123"
}


### Get All Users
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/users

### Get User by ID
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/users/1


###LOCAL DEVELOPMENT

### Get All Users
POST https://2ff94588cbf6.ngrok-free.app/api/v1/auth/user
Content-Type: application/json

{
"action":"fetchAllUsers"
}

###
GET https://2ff94588cbf6.ngrok-free.app/api/v1/auth?action=fetchAllUsers


### Get User by ID
GET https://2ff94588cbf6.ngrok-free.app/api/v1/auth/

{
  "action": "fetchUserById",
  "id": 8
}




### Register User
POST https://2ff94588cbf6.ngrok-free.app/api/v1/auth/
Content-Type: application/json

{
  "action":"register",
  "username": "Timoothy",
  "firstName": "omosh",
  "lastName": "Tim",
  "phoneNumber": "0786304557",
  "email": "timoothy@gmail.com",
  "role": "USER"
}


### Login User
POST https://2ff94588cbf6.ngrok-free.app/api/v1/auth/
Content-Type: application/json

{
  "action":"userLogin",
  "username": "Timoothy",
  "password": "nthuli"
}




### Change Password
POST https://2ff94588cbf6.ngrok-free.app/api/v1/auth/change-password
Content-Type: application/json

{
  "username": "Timoothy",
  "newPassword": "nthuli"
}



