### GET request to example server
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/

### GET Developers
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers

### GET Developers by Id
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers1

### ADD Developers
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Ian Nthuli",
  "techStack": ["Kotlin", "Jetpack-compose", "Spring-Boot","XML"]
}

### Login User
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "securePassword123"
}


### Register User
POST https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/register
Content-Type: application/json

{
  "username": "john_doe",
  "password": "securePassword123"
}


### Get All Users
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/users

### Get User by ID
GET https://springbootbackend-7b88ebb3ac07.herokuapp.com/api/v1/auth/users/1



